---
upstream_project_url: https://github.com/authselect/authselect
issue_repository: https://github.com/authselect/authselect

upstream_package_name: authselect
specfile_path: authselect.spec

actions:
  post-upstream-clone:
    - cp rpm/authselect.spec.in authselect.spec
    - sed -i "s/@PACKAGE_VERSION@/99/g" authselect.spec
    - sed -i "s/@RELEASE_NUMBER@%{?dist}/%autorelease/g" authselect.spec

jobs:
  # Produce COPR builds on push
  - job: copr_build
    trigger: commit
    targets:
      - centos-stream-9
      - centos-stream-8

  # Produce COPR build on each pull request
  - job: copr_build
    trigger: pull_request
    targets:
      - centos-stream-9
      - centos-stream-8
