passwd:     files {if "with-altfiles":altfiles }winbind systemd    {exclude if "with-custom-passwd"}
group:      files {if "with-altfiles":altfiles }winbind systemd    {exclude if "with-custom-group"} {exclude if "with-group-merging"}
group:      files [SUCCESS=merge] {if "with-altfiles":altfiles [SUCCESS=merge] }winbind [SUCCESS=merge] systemd    {exclude if "with-custom-group"} {include if "with-group-merging"}
